services:
  nfs-checker:
    image: nfs-checker:latest
    restart: always
    environment:
      - NFS1=nfs-server:/export/test
      - TIMEOUT=60
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/nfs-ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
  app:
    image: hello-world
    restart: always
    depends_on:
      nfs-checker:
        condition: service_healthy
    volumes:
      - /mnt/nfs1:/mnt/nfs1:ro
    networks:
      - app-network
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    environment:
      - SHARED_DIRECTORY=/export/test
    volumes:
      - nfs-data:/export/test
    ports:
      - "2049:2049"
      - "111:111"
      - "20048:20048"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    networks:
      - app-network
volumes:
  nfs-data:
networks:
  app-network:
    driver: bridge
