services:
  nfs-checker:
    image: nfs-checker:latest
    restart: always
    environment:
      - NFS1=192.168.1.100:/path/to/share1
      - NFS2=192.168.1.100:/path/to/share2
      - TIMEOUT=120  # Optional: seconds to wait before failing (omit for indefinite)
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/nfs-ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    app:
      # Replace 'hello-world' with your desired image (e.g., 'nginx:latest' to serve files from /mnt/nfs1)
      image: hello-world
      restart: always
      depends_on:
        nfs-checker:
          condition: service_healthy
      volumes:
        - /mnt/nfs1:/mnt/nfs1:ro  # Mounts NFS share; not used by hello-world but included for consistency
