name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build nfs-checker image
        run: |
          docker build -t nfs-checker:latest ./nfs-checker

      - name: Run docker-compose
        run: |
          docker-compose up -d
          timeout 60s bash -c "until docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q nfs-checker) | grep -q 'healthy'; do sleep 5; done"
          docker-compose logs app | grep "Hello from Docker!"

      - name: Clean up
        if: always()
        run: |
          docker-compose down -v
