name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build nfs-checker image
      - name: Build nfs-checker image
        run: |
          docker build -t nfs-checker:latest ./nfs-checker

      # TODO set this up correctly when I have time
      # Run docker-compose to test the setup
      # - name: Run docker-compose
      #   run: |
      #     docker-compose up -d
      #     # Wait for nfs-checker to become healthy
      #     timeout 60s bash -c "until docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q nfs-checker) | grep -q 'healthy'; do sleep 5; done"
      #     # Check app logs for hello-world output
      #     docker-compose logs app | grep "Hello from Docker!"

      # # Clean up
      # - name: Clean up
      #   if: always
      #   run: |
      #     docker-compose down -v
